spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authDB
    username: root
    password: 9462
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: Auth-Security
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: auth-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.esliceyament.shared.payload

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


my:
  secret:
    key: IbF4ZFKW81ak4lW7xai8hbtwZf1Mpxyj

server:
  port: 8081