spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Auth-Security  # Adding Auth-Service route
          uri: lb://AUTH-SECURITY  # Load balanced URI for the Auth service
          predicates:
            - Path=/authenticate/**, /users/profile/**

        - id: Product-Service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**, /images/**, /ratings/**
          filters:
            - name: JwtAuthenticationFilter

        - id: Category-Service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/categories/**, /attributes/**
          filters:
            - name: JwtAuthenticationFilter

        - id: Inventory-Service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**
          filters:
            - name: JwtAuthenticationFilter

        - id: Order-Service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/cart/**, /discount/**, /order/**, /return/**
          filters:
            - name: JwtAuthenticationFilter

        - id: Favourites-Service
          uri: lb://FAVOURITES-SERVICE
          predicates:
            - Path=/favourites/**
          filters:
            - name: JwtAuthenticationFilter

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    feign: DEBUG


my:
  secret:
    key: IbF4ZFKW81ak4lW7xai8hbtwZf1Mpxyj