spring:
  application:
    name: Service-Discovery
  cloud:
    discovery:
      client:
        simple:
          eureka:
            enabled: true
  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false

server:
  port: 8761