spring:
  datasource:
    url: jdbc:mysql://localhost:3306/favouritesdb
    username: root
    password: 9462
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: Favourites-Service


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8086