spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/categoriesdb
    username: postgres
    password: 9462
    driver-class-name: org.postgresql.Driver
  application:
    name: Category-Service


  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

