spring:
  application:
    name: Order-Service
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: 9462
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8085

