spring:
  data:
    mongodb:
      uri: mongodb+srv://new_user:1111@cluster0.vie0f.mongodb.net/products?retryWrites=true&w=majority&appName=Cluster0
  application:
    name: Product-Service
  kafka:
      bootstrap-servers: localhost:9092
      consumer:
        group-id: product-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
        properties:
          value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          spring.json.trusted.packages: com.esliceyament.shared.payload


image:
  upload:
    directory: C:/Users/User/IdeaProjects/Images

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082