spring:
  application:
    name: Inventory-Service
  datasource:
    url: jdbc:mysql://localhost:3306/inventorydb
    username: root
    password: 9462
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
      bootstrap-servers: localhost:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      consumer:
        group-id: inventory-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
        properties:
          value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          spring.json.trusted.packages: com.esliceyament.shared.payload

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8084


